version: '3.8'

services:
  backend:
    build:
      context: ../..
      dockerfile: app/backend/Dockerfile
    environment:
      - DATABASE_URL=mysql://mokak:_mokak123@db:3306/testDB
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=redis
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_SECRET_URL=${VAULT_SECRET_URL}
    depends_on:
      - db
      - redis
    volumes:
      - prisma-migrations:/app/prisma/migrations

  db:
    image: ccxz84/morak-mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=anl@oiq12^&()
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - "3306"

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  mysql-data:
  prisma-migrations:
