version: '3.8'

services:
  backend:
    build:
      context: ../..
      dockerfile: app/backend/Dockerfile
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_DATABASE_NAME}
      - REDIS_HOST=redis
      - DOMAIN=${DOMAIN}
      - PORT=${PORT}
    depends_on:
      - db
      - redis
    ports:
     - "${PORT}:${PORT}"
  db:
    image: ccxz84/morak-mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  redis:
    image: redis:alpine
    expose:
      - "6379"

volumes:
  mysql-data:
